# Generated by Django 3.1.7 on 2021-04-01 10:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('witswap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='witnettoethereumswap',
            name='unconfirmed_funds_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='witnettoethereumswap',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
