# Generated by Django 3.2.3 on 2021-05-31 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('witswap', '0002_auto_20210401_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custodian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Custodian',
                'verbose_name_plural': 'Custodians',
            },
        ),
        migrations.AddField(
            model_name='configuration',
            name='last_custodian_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='witswap.custodian'),
        ),
        migrations.AddField(
            model_name='ethereumtowitnetswap',
            name='custodian',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='witswap.custodian'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='witnettoethereumswap',
            name='custodian',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='witswap.custodian'),
            preserve_default=False,
        ),
    ]
