# Generated by Django 3.2.3 on 2021-05-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('witswap', '0003_auto_20210531_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='custodian',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
