# Generated by Django 3.2.3 on 2021-05-31 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('witswap', '0004_custodian_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethereumtowitnetswap',
            name='custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='witswap.custodian'),
        ),
        migrations.AlterField(
            model_name='witnettoethereumswap',
            name='custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='witswap.custodian'),
        ),
    ]
