# Generated by Django 3.2.3 on 2021-05-31 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('witswap', '0005_auto_20210531_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='witnettoethereumswap',
            name='custodian',
        ),
        migrations.AddField(
            model_name='witnetaddress',
            name='custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='witswap.custodian'),
        ),
    ]
