# Generated by Django 3.2.3 on 2021-06-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('witswap', '0006_auto_20210531_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethereumtowitnetswap',
            name='initial_amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='ethereumtowitnetswap',
            name='swapped_amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='witnettoethereumswap',
            name='total_funds_received',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='witnettoethereumswap',
            name='total_swapped',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='witnettoethereumswap',
            name='unconfirmed_funds_received',
            field=models.BigIntegerField(default=0),
        ),
    ]
