# Generated by Django 3.2.3 on 2021-06-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('witswap', '0007_auto_20210601_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='is_node_synced',
            field=models.BooleanField(default=True),
        ),
    ]
