# Generated by Django 3.2.3 on 2021-06-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('witswap', '0008_configuration_is_node_synced'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='fee_percentage',
            field=models.IntegerField(default=5),
        ),
    ]
