# Generated by Django 3.2.3 on 2021-09-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('witswap', '0009_configuration_fee_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='minimum_swap_amount',
            field=models.IntegerField(default=10000000000000, help_text='Remember to add the 9 decimals'),
        ),
    ]
